language: node_js
cache:
    directories:
        - node_modules
install:
    - npm install
notifications:
    email: false
node_js:
    - '7'
    - '6'
    - '4'
before_script:
    - npm prune
script:
    - npm test
after_success:
    - npm run coveralls
branches:
    except:
        - /^v\d+\.\d+\.\d+$/
